### ISSUE TITLE
current master does not build

### ISSUE THREAD

**Issue by hgschmie** [HubSpot/Blazar#164]
fails with 

Failed to execute goal on project BlazarService: Could not resolve dependencies for project com.hubspot:BlazarService:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.hubspot:SingularityBase:jar:0.4.9-hs_stable-SNAPSHOT, com.hubspot:SingularityClient:jar:0.4.9-hs_stable-SNAPSHOT: Could not find artifact com.hubspot:SingularityBase:jar:0.4.9-hs_stable-SNAPSHOT in snapshots

Guess that there should not be a hubspot specific version in there.

**Comment by jhaber** [comment]
Sorry about that, I forgot those snapshots aren't pushed to maven central. I'll update it to use a release version

**Comment by jhaber** [comment]
I updated it to use the Singularity 0.4.11 release and also pushed a release of Blazar to Maven Central (version 0.3). You can see an example dropwizard config with all required fields [here](https://github.com/HubSpot/Blazar/blob/master/Blazar.yaml). There isn't much documentation and so far we've been developing it specifically for our own use so it may be hard to get up and running. Let us know if you run into any other issues.
