### ISSUE TITLE
(blazar) Cache build (sub) directories

### ISSUE THREAD

**Issue by jonathanwgoodwin** [HubSpot/Blazar#41]
Support trying to pull directories from S3 to speed up java builds.
Used to warm maven's cache etc.
cc: @jhaber 

- [x] S3 bucket
- [x] Key structure `{blazar-coordinates}/{md5(file-path)}`
- [ ] Executor directory check
- [ ] Executor download and un-tar
- [ ] Executor upload after build +  md5sum

**Comment by jhaber** [comment]
We can also upload a .md5 in addition to a .tgz and compare the current checksum to the one in S3 so that we don't need to re-upload if nothing in the directory changed

**Comment by jonathanwgoodwin** [comment]
:100: added that to the list

**Comment by jonathanwgoodwin** [comment]
cc: @tpetr

**Comment by jonathanwgoodwin** [comment]
This is done
